// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkdbuItyXN17oSOpymD7ORUjyasUgKFzg',
    appId: '1:68296397689:web:35433a467bed06033415a8',
    messagingSenderId: '68296397689',
    projectId: 'homefix-mobile-app',
    authDomain: 'homefix-mobile-app.firebaseapp.com',
    storageBucket: 'homefix-mobile-app.firebasestorage.app',
    measurementId: 'G-1GTCCQZ2K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeexUGJ3IVZee3H-1ldfdlO6-CrpU0mP8',
    appId: '1:68296397689:android:e60c937b2a789e8e3415a8',
    messagingSenderId: '68296397689',
    projectId: 'homefix-mobile-app',
    storageBucket: 'homefix-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADNiupppEH85l5Ta5fkRCUuuYH9b7IC6Q',
    appId: '1:68296397689:ios:f4d78cd100257f463415a8',
    messagingSenderId: '68296397689',
    projectId: 'homefix-mobile-app',
    storageBucket: 'homefix-mobile-app.firebasestorage.app',
    iosBundleId: 'com.homefix.homefixApp',
  );
}
